site_name: GROBID NER Documentation
repo_url: https://github.com/kermitt2/grobid-ner/
repo_name: GitHub
theme: readthedocs
site_description: Documentation for GROBID NER
docs_dir: grobid-ner/doc
include_search: true
pages:
- Home: 'index.md'
- About:
  - 'Licence': 'Licence.md'
- User Manual:
  - 'Build and Install': 'build-and-install.md'
  - 'Using GROBID NER': 'using-grobid-ner.md'
  - 'Class and Senses': 'class-and-senses.md'
  - 'Annotation Guidelines': 'annotation-guidelines.md'
  - 'Annotation examples': 'annotation-examples.md'
  - 'Datasets and training': 'training-ner-model.md'
  - 'Generate training data': 'generate-training-data.md'
